### ISSUE TITLE
Unable to query any data from TinaCloud

### ISSUE THREAD

**Issue by ACoolTurtle** [tinacms/tina-graphql-gateway#293]
## Description

No matter what the request is, TinaCloud's response is "Something went wrong".

### Steps to reproduce

Make a Graphql request to the Tina Endpoint

### Expected result

Data should be returned

### Actual result

`{"message":"Something went wrong."}`
A vague error is returned.

#### Tinacms Package Versions

```

react-tinacms-editor@npm:0.41.1
react-tinacms-inline@npm:0.41.1
tinacms@npm:0.41.1

```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |  Chrome 91.0.4472.106       |
| os      |     Windows 10, WSL 2 Ubuntu |
| node    |        15.7.0 |
| npm     |       7.4.3  |

**Comment by DirtyF** [comment]
@ACoolTurtle Same here, getting a 500 error on content.tinajs.io 🤔

**Comment by DirtyF** [comment]
@ACoolTurtle We just deployed a fix, it should be good now.

**Comment by ACoolTurtle** [comment]
This issue still remains, however rather than a 500 error, I get a 404 with `Something went wrong`

**Comment by DirtyF** [comment]
Could you share a bit more information, what actions did you take?

**Comment by ACoolTurtle** [comment]
Just the standard request

```
query GetMain($relativePath: String!) {
			getPageDocument(relativePath: $relativePath) {
				data {
					... on Page_Doc_Data {
						slug
						seo {
							description
							lang
							image
							title
							meta {
								content
								name
							}
						}
						menuLinks {
							title
							path
						}
						components {
							... on Carousel_Data {
								__typename
								images {
									image
								}
								height
								fade
								fadeTime
								fadeOnce
								delay
								toggle_fade_direction
							}
							... on FreeStyle_Data {
								__typename
								mdx
							}
							... on Title_Data {
								__typename
								titleText
								bodyTextMdx
								mdx
								fade
								toggle_fade
								fadeOpts
								fadeTime
								fadeOnce
								delay
								toggle_fade_direction
							}
							... on LinkGrid_Data {
								__typename
								grid {
									titleText
									description
									image
									mdx
									link
									linkText
								}
								fade
								fadeOpts
								fadeTime
								fadeOnce
								delay
								toggle_fade_direction
							}
							... on Banner_Data {
								__typename
								image
								height
								enableCenter
								mdx
								enableOffset
								offsetMdx
							}
							... on Section_Data {
								__typename
								mdx
								toggle_fade
								fade
								fadeOpts
								fadeTime
								fadeOnce
								delay
								toggle_fade_direction
							}
							... on SideBySide_Data {
								__typename
								left {
									enableIcon
									mdx
									toggle_fade_direction
									delay
									fadeOnce
									fadeTime
									fadeOpts
									enable_fade
								}
								right {
									enableIcon
									mdx
									toggle_fade_direction
									delay
									fadeOnce
									fadeTime
									fadeOpts
									enable_fade
								}
							}
						}
					}
				}
			}
		}
```

It works on the LocalClient just fine with the local version being `0.2.51`.

**Comment by DirtyF** [comment]
@ACoolTurtle Do you by any chance have a public repository to share so that we can reproduce the issue?

**Comment by logan-anderson** [comment]
@ACoolTurtle Thanks for submitting this issue! if your unable to share your code that is more then ok! the only thing we would need to reproduce this error is your schema.ts file and any other files that are imported from it. 

Since its working on your local environment and not on Tina Cloud I have a feeling it could be one of the following issues.

1. You have not committed and pushed your schema.ts and all generated files to Github.
2. The cloud version is out of date with the local version.
    * This is an issue on our end. We are working to find a solution to ensure the cloud version is up to date with the latest local version.  @jamespohalloran do you happen to know that version of `tina-graphql-gateway` we are currently using on Tina Cloud?

**Comment by jamespohalloran** [comment]
It's currently using `"tina-graphql": "0.1.14"`

**Comment by ACoolTurtle** [comment]
@logan-anderson Sure, here is my schema, and the constants that are used. Thanks for your help
[schema.ts.txt](https://github.com/tinacms/tina-graphql-gateway/files/6735000/schema.ts.txt)
[schemaConstants.ts.txt](https://github.com/tinacms/tina-graphql-gateway/files/6734986/schemaConstants.ts.txt)

**Comment by logan-anderson** [comment]
@ACoolTurtle Thanks! for the files.

I am not 100% sure but it seems that it is most likely the latter (point 2) I have a feeling that https://github.com/tinacms/tina-graphql-gateway/pull/304/files will fix it when it is merged and when Tina cloud bumps its version of "tina-graphql": "0.1.18". 

We apologize for the inconvenience and will update you when it's working.

It's great to see such advanced usage of Tina Cloud! Thanks!

**Comment by ACoolTurtle** [comment]
Thanks for your support! I really like the idea of Tina

**Comment by logan-anderson** [comment]
@ACoolTurtle I just tested this and it looks like it is fixed.
